# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  
  # Vagrant box
	config.vm.box = "nritholtz/ubuntu-14.04.1"

  # Vagrant hostname
  config.vm.hostname = "Chowan-avalkov-VMVM"
  
  # VB configuration   
	config.vm.provider "virtualbox" do |vb|
  # Display the VirtualBox GUI when booting the machine
     vb.gui = true
  # Set VM name
	 vb.name="Chowan-avalkov-VMVM"
  # Assign 2Gb of RAM to VM	 
     vb.memory = "2048"
  # Turning off usb
	 vb.customize ["modifyvm", :id, "--usb", "off"]
	 vb.customize ["modifyvm", :id, "--usbehci", "off"]
   end
 
  # Provisioning script
  
   config.vm.provision "shell", inline: <<-SHELL 
    sudo gsettings set org.gnome.desktop.screensaver lock-enabled false
  # Change user full name to vagrant
	sudo chfn -f "vagrant" vagrant
  # Install Java, Ant, Maven and Git
    sudo apt-get update
	sudo apt-get install -y openjdk-7-jdk
	sudo apt-get install -y ant
	sudo apt-get install -y maven
	sudo apt-get install -y git
  # Git clone tool to folder on Desktop
	sudo git clone https://github.com/SoftwareEngineeringToolDemos/ICSE-2014-VMVM.git "Desktop/ICSE-2014-VMVM"
	cd Desktop
  # Change ownership of folder to user "vagrant" for ease of use
	sudo chown -v -R vagrant ICSE-2014-VMVM
	sudo reboot
   SHELL
end
